---
# Base variables


apt_packages:
  - ack-grep
  - aria2
  - build-essential
  - curl
  - devscripts
  - emacs24-nox
  - exuberant-ctags
  - flake8
  - g++
  - gcc
  - git
  - htop
  - httpie
  - iftop
  - iotop
  - ipython
  - ipython3
  - jq
  - language-pack-ru
  - libxml2-dev
  - libxslt-dev
  - libyaml-dev
  - ncurses-term
  - pkg-config
  - python3-all
  - python3-all-dev
  - python3-cffi
  - python3-flake8
  - python3-hacking
  - python3-ipdb
  - python3-jedi
  - python3-pep8
  - python3-pep8-naming
  - python3-pip
  - python3-stdeb
  - python3-virtualenv
  - python-all
  - python-all-dev
  - python-autopep8
  - python-cffi
  - python-dev
  - python-flake8
  - python-hacking
  - python-ipdb
  - python-jedi
  - python-pep8
  - python-pep8-naming
  - python-pip
  - python-stdeb
  - python-virtualenv
  - ruby
  - shellcheck
  - silversearcher-ag
  - tig
  - tmux
  - tmuxinator
  - vim
  - wget
  - yamllint
  - zsh

unwanted_apt_packages:
  - puppet
  - puppet-common
  - chef
  - chef-zero

ssh_known_hosts:
  - github.com

docker_prerequisites:
  - apt-transport-https
  - ca-certificates
