---
# Install Pythons in Pyenv and create Decapod virtualenv


- name: Install Pythons
  command: bash -ic "pyenv install -s {{ item }}"
  with_items: "{{ pyenv_pythons }}"
  tags:
    # -s flags for pyenv install tells that it skips if nothing to do
    - skip_ansible_lint

- name: Check if Decapod virtualenv exists
  stat: path="{{ pyenv_root }}/versions/decapod"
  register: decapod_virtualenv

- name: Create Decapod virtualenv
  command: bash -ic "pyenv virtualenv {{ decapod_python }} {{ venv }}"
  when: not decapod_virtualenv.stat.exists

- name: Install requirements in PyEnv virtualenv
  command: bash -ic "pyenv activate {{ venv }} && pip install -r {{ item }} -c constraints.txt"
           chdir=/vagrant
  with_items:
    - build-requirements.txt
    - test-requirements.txt
    - optional-requirements.txt
  tags:
    # This is to update requirements
    - skip_ansible_lint

- name: Install buildtools
  command: bash -ic "pyenv activate {{ venv }} && pip install -c constraints.txt -e ./buildtools"
  tags:
    - skip_ansible_lint

- name: Update PyEnv virtualenv
  command: bash -ic "pyenv activate {{ venv }} && pip install -e {{ item }} -c constraints.txt"
           chdir=/vagrant
  with_items:
    - backend/common
    - backend/migration
    - backend/api
    - backend/controller
    - plugins/alerts/emails
    - plugins/playbook/server_discovery
    - plugins/playbook/playbook_helloworld
  tags:
    # This is to update requirements
    - skip_ansible_lint

- name: Ensure that shortcut for PyEnv virtualenv is installed
  lineinfile: dest=.bashrc
              line="alias ve='pyenv activate {{ venv }}'"
              state=present
